import * as caeser from './caeser.ts';
import * as vigenere from './vigenere.ts';
import * as skytale from './skytale.ts'

const caeserText = `ZAN BWQHA DAEJV

DAEJV SWN BWQH, QJZ KXCHAEYD AN SAEPAN JEYDPO VQ PQJ DWPPA, WHO OAEJA VEACA PWACHEYD WQB ZEA SAEZA VQ PNAEXAJ, OK OAQBVPA AN ZAJJKYD, SAJJ AN JWYD RKHHXNWYDPAI PWCASANG WXAJZO JWYD DWQOA GWI. ›AO EOP EJ SWDNDAEP AEJA OYDSANA HWOP,‹ OWCPA AN, ›QJZ AEJ IQADOAHECAO CAOYDWABP, OK AEJA VEACA FWDN WQO FWDN AEJ XEO EJ ZAJ OLWAPAJ DANXOP EJO BAHZ VQ PNAEXAJ. QJZ SAJJ IWJ OEYD JKYD ZWXAE DEJHACAJ QJZ OYDHWBAJ GKAJJPA! WXAN JAEJ, ZW IQOO IWJ ZEA WQCAJ WQBDWXAJ, ZWIEP OEA ZEA FQJCAJ XWAQIA JEYDP XAOYDWAZECP, ZQNYD ZEA DAYGA EJ AEJAJ CWNPAJ ZNEJCP KZAN CWN ZWRKJHWAQBP. SEA OKHH ZW AEJAN VQN NQDA GKIIAJ QJZ OAEJAO HAXAJO BNKD SANZAJ!‹ AN OAPVPA OEYD, OWIIAHPA OAEJA CAZWJGAJ QJZ QAXANHACPA, SEA AN OAEJA OYDQHPANJ RKJ ZEAOAN XQANZA BNAE IWYDAJ GKAJJPA. HWJCA SWN WHHAO JWYDOEJJAJ RANCAXHEYD, LHKAPVHEYD BEAHO EDI SEA OYDQLLAJ RKJ ZAJ WQCAJ. ›EYD SAEOO, SWO EYD PQA,‹ NEAB AN WQO, ›EYD DAENWPA ZEA ZEYGA PNEJA, ZEA DWP WQYD AEJA VEACA QJZ GWJJ IAEJA IEP WQOPNAEXAJ, OK XNWQYDA EYD IEYD JEYDP HWAJCAN VQ MQWAHAJ.‹

DAEJV ANDKX OEYD WHOK, OAPVPA OAEJA IQAZAJ CHEAZAN EJ XASACQJC, CEJC MQAN QAXAN ZEA OPNWOOA, ZAJJ SAEPAN SWN ZAN SAC JEYDP, SK ZEA AHPANJ ZAN ZEYGAJ PNEJA SKDJPAJ, QJZ DEAHP QI EDNA WNXAEPOWIA QJZ PQCAJZNAEYDA PKYDPAN WJ. ZEA AHPANJ XAOWJJAJ OEYD JEYDP HWJCA, ›CHAEYD QJZ CHAEYD CAOAHHP OEYD CANJ,‹ IAEJPAJ OEA QJZ SEHHECPAJ AEJ. JQJ SWNZ ZEA ZEYGA PNEJA DAEJVAJO BNWQ QJZ PNEAX ZEA XAEZAJ VEACAJ WQO. DAEJV DWPPA CQPA PWCA QJZ XNWQYDPA OEYD RKJ GAEJAN WJZANJ WNXAEP VQ ANDKHAJ WHO RKJ OAEJAN AECAJAJ BWQHDAEP. JQN ZWJJ QJZ SWJJ CEJC AN IEP DEJWQO QJZ OWCPA ›AO CAOYDEADP XHKOO, ZWIEP IEN ZEA NQDA DANJWYD ZAOPK XAOOAN OYDIAYGP: IWJ RANHEANP OKJOP WHHAO CABQADH ZWBQAN.‹

WXAN ZEA ZEYGA PNEJA SWN JEYDP IEJZAN BWQH. ›HEAXAN DAEJV,‹ OLNWYD OEA AEJAO PWCAO, ›SWNQI OKHHAJ SEN QJO ZWO HAXAJ KDJA JKP OWQAN IWYDAJ QJZ QJOANA XAOPA FQCAJZVAEP RANGQAIIANJ? EOP AO JEYDP XAOOAN, SEN CAXAJ ZEA XAEZAJ VEACAJ, ZEA FAZAJ IKNCAJ AEJAJ IEP EDNAI IAYGANJ EI XAOPAJ OYDHWBA OPKANAJ, QJOANI JWYDXWN, QJZ ZAN CEXP QJO AEJAJ XEAJAJOPKYG ZWBQAN? ZAJ XEAJAJOPKYG OPAHHAJ SEN WJ AEJAJ OKJJECAJ LHWPV DEJPAN ZWO DWQO QJZ XAGQAIIANJ QJO SAEPAN JEYDP ZWNQI. ZEA XEAJAJ XNWQYDAJ JEYDP CADQAPAP QJZ JEYDP EJO BAHZ CAPNEAXAJ VQ SANZAJ: OEA BHEACAJ WQO, BEJZAJ ZAJ SAC JWYD DWQO RKJ OAHXOP SEAZAN QJZ OWIIAHJ DKJEC, KDJA ZWOO AO QJO ZEA CANEJCOPA IQADA IWYDP.‹ ›ZQ DWOP SEA AEJA RANOPWAJZECA BNWQ CAOLNKYDAJ,‹ WJPSKNPAPA DAEJV, ›ZAEJAJ RKNOYDHWC SKHHAJ SEN KDJA VWQZANJ WQOBQADNAJ: WQOOANZAI OYDIAYGP QJZ JWADNP ZAN DKJEC XAOOAN WHO ZEA VEACAJIEHYD QJZ HWAOOP OEYD WQYD HWAJCAN WQBXASWDNAJ.‹

ZAN JWYDXWN CWX BQAN ZEA XAEZAJ VEACAJ CANJA AEJAJ XEAJAJOPKYG. ZEA XEAJAJ BHKCAJ QJANIQAZHEYD RKI BNQADAJ IKNCAJ XEO VQI OLWAPAJ WXAJZ WQO QJZ AEJ, QJZ BQAHHPAJ ZAJ OPKYG IEP ZAI OYDKAJOPAJ DKJEC, OK ZWOO DAEJV EI DANXOP AEJAJ CWJVAJ GNQC RKHH DANWQOJADIAJ GKJJPA.

OEA OPAHHPAJ ZAJ GNQC WQB AEJ XNAPP, ZWO KXAJ WJ ZAN SWJZ EJ EDNAN OYDHWBGWIIAN XABAOPECP SWN, QJZ SAEH OEA BQANYDPAPAJ, AN GKAJJPA EDJAJ CAOPKDHAJ SANZAJ KZAN ZEA IWAQOA GKAJJPAJ ZWNQAXAN CANWPAJ, OK DKHPA PNEJA AEJAJ OPWNGAJ DWOAHOPKYG DANXAE QJZ HACPA EDJ JAXAJ EDN XAPP, ZWIEP OEA EDJ, KDJA QJJKAPECANSAEOA WQBVQOPADAJ, IEP ZAN DWJZ ANNAEYDAJ QJZ ZEA QJCAXAPAJAJ CWAOPA RKJ ZAI XAPPA WQO RANFWCAJ GKAJJPA.

ZAN BWQHA DAEJV RANHEAOO ZWO XAPP JEYDP CANJA RKN IEPPWC: ›SAN BNQAD WQBOPADP,‹ OLNWYD AN, ›OAEJ CQP RANVADNP.‹ AEJAO IKNCAJO, WHO AN OK WI DAHHAJ PWCA JKYD EJ ZAJ BAZANJ HWC QJZ RKJ ZAI HWJCAJ OYDHWB WQONQDPA, OLNWYD AN VQ OAEJAN BNWQ ›ZEA SAEXAN HEAXAJ ZEA OQAOOECGAEP,‹ QJZ ZQ JWOYDAOP RKJ ZAI DKJEC, AO EOP XAOOAN, ADA AN RKJ ZEN WHHAEJ WQOCACAOOAJ SENZ, ZWOO SEN ZWBQAN AEJA CWJO IEP AEJAI FQJCAJ CWAJOHAEJ ANDWJZAHJ.‹ ›WXAN JEYDP ADAN,‹ ANSEZANPA PNEJA, ›WHO XEO SEN AEJ GEJZ DWXAJ, ZWO OEA DQAPAP. OKHH EYD IEYD APSW IEP ZAJ FQJCAJ CWAJOAJ LHWCAJ QJZ IAEJA GNWABPA ZWXAE QJJKAPECANSAEOA VQOAPVAJ?‹ ›IAEJOP ZQ,‹ OWCPA DAEJV, ›ZAN FQJCA SANZA CWAJOA DQAPAJ? DAQPVQPWCA CADKNYDAJ ZEA GEJZAN JEYDP IADN: OEA PQJ JWYD EDNAI AECAJAJ SEHHAJ, SAEH OEA OEYD GHQACAN ZQAJGAJ WHO ZEA AHPANJ, CANWZA SEA FAJAN GJAYDP, ZAN ZEA GQD OQYDAJ OKHHPA QJZ ZNAE WIOAHJ JWYDFWCPA.‹ ›K,‹ WJPSKNPAPA PNEJA, ›ZAI OKHH AO OYDHAYDP XAGKIIAJ, SAJJ AN JEYDP PQP, SWO EYD OWCA. AEJAJ OPKYG SEHH EYD JADIAJ QJZ IEP QJCAVWADHPAJ OYDHWACAJ EDI ZEA DWQP CANXAJ. OEADOP ZQ, DAEJV,‹ NEAB OEA EJ EDNAI AEBAN QJZ BWOOPA ZAJ OPKYG, IEP ZAI OEA ZEA IWAQOA RANFWCAJ SKHHPA, ›OEADOP ZQ, OK SEHH EYD WQB EDJ HKOOYDHWCAJ.‹ OEA DKHPA WQO, PNWB WXAN QJCHQAYGHEYDANSAEOA ZAJ DKJECGNQC QAXAN ZAI XAPPA. ZAN GNQC OLNWJC SEZAN ZEA SWJZ QJZ BEAH EJ OYDANXAJ DANWX, QJZ ZAN OYDKAJA DKJEC BHKOO WQB ZAJ XKZAJ. ›ZW HEACP JQJ ZEA CWJO IEP ZAI FQJCAJ CWAJOHAEJ,‹ OWCPA DAEJV, ›QJZ XNWQYDP JEYDP CADQAPAP VQ SANZAJ. WXAN AEJ CHQAYG EOP AO, ZWOO IEN ZAN GNQC JEYDP WQB ZAJ GKLB CABWHHAJ EOP, SEN DWXAJ WHHA QNOWYDA, IEP QJOANI OYDEYGOWH VQBNEAZAJ VQ OAEJ.‹ QJZ ZW AN EJ AEJAN OYDANXA JKYD APSWO DKJEC XAIANGPA, OK HWJCPA AN ZWJWYD QJZ OLNWYD CWJV RANCJQACP ›ZWO NAOPYDAJ, BNWQ, SKHHAJ SEN QJO JKYD OYDIAYGAJ HWOOAJ QJZ ZWJJ JWYD ZAI CADWXPAJ OYDNAYGAJ AEJ SAJEC WQONQDAJ, SWO PQPO, SAJJ SEN APSWO OLWAPAN WHO CASKADJHEYD WQBOPADAJ, ZAN PWC EOP ZKYD JKYD HWJC CAJQC.‹ ›FW,‹ WJPSKNPAPA PNEJA, ›IWJ GKIIP EIIAN JKYD VQ NAYDPAN VAEP. SAEOOP ZQ, ZEA OYDJAYGA SWN AEJIWH VQN DKYDVAEP AEJCAHWZAJ, IWYDPA OEYD WQB ZAJ SAC, GWI WXAN VQN GEJZPWQBA WJ. RKN ZAI DWQOA OPQANVPA OEA JKYD QAXAN ZAJ VWQJ QJZ OWCPA ›AEHAJ PQP JEYDP CQP.‹`;

const vigenereText = `UEQPCVCKAHVNRZURNLAOKIRVGJTDVRVRICVIDLMYIYSBCCOJQSZNYMBVDLOKFSLMWEFRZAVIQMFJTDIHCIFPSEBXMFFTDMHZGNMWKAXAUVUHJHNUULSVSJIPJCKTIVSVMZJENZSKAHZSUIHQVIBXMFFIPLCXEQXOCAVBVRTWMBLNGNIVRLPFVTDMHZGNMWKRXVRQEKVRLKDBSEIPUCEAWJSBAPMBVSZCFUEGITLEUOSJOUOHUAVAGZEZISYRHVRZHUMFRREMWKULKVKGHAHFEUBKLRGMBJIHLIIFWMBZHUMPLEUWGRBHZOLCKCWTHWDSILDAGVNEMJFRVQSVIQMUVSWMZCTHIIWGDJSXEOWSJTKIHKEQ`;


// console.log(caeser.countLetters(caeserText));
// console.log(caeser.shift(caeserText, 4));

// const split = vigenere.split(vigenereText, 5);

// const [text1, text2, text3, text4, text5] = split;

// const decode1 = caeser.shift(text1, 9);
// const decode2 = text2;
// const decode3 = caeser.shift(text3, 23);
// const decode4 = caeser.shift(text4, 18);
// const decode5 = caeser.shift(text5, 12)

// console.log(vigenere.join([decode1, decode2, decode3, decode4, decode5], 5));
// console.log(caeser.ABC[26 - 9], caeser.ABC[0], caeser.ABC[26 - 23], caeser.ABC[26 - 18], caeser.ABC[26 - 12]);

// console.log(vigenere.decode(vigenereText, "RADIO"));




// console.log(decode1, decode2);

// text1

// split.forEach((val, idx) => {
//     console.log(`---${idx}---`);
//     console.log(caeser.countLetters(val));
// });

// vigenere.findLetters(vigenereText);

// console.log(vigenere.decode(vigenereText, ))

// skytale.default(`MNIEWAEASLONIMTILNNE_XL___F_M_`);
// skytale.default(`FLTUEM_ELAVSINESXNRE__SLWUCUOEHNLBLG`);

// console.log(caeser.shift("SKHHIWJJBAHET", 4));

// console.log(caeser.countLetters(caeserText, true));

// console.log(caeser.shift(caeserText, 4));